### ISSUE TITLE
cimport error

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq#229]
while importing cpp using cimport this error 
```

Traceback (most recent call last):
  File "/home/withsj/.local/bin/csq", line 35, in <module>
    compiled_code = Compile(lines)
  File "/home/withsj/.local/bin/Compiler/Parser/parser.py", line 490, in Compile
    code_string += "\n//" + node.path + "\n" + visit_CImportNode(node) + "\n"
  File "/home/withsj/.local/bin/Compiler/Parser/parser.py", line 553, in visit_CImportNode
    module = open(_curr_path + "/" + node.path + ".cpp", "r")
FileNotFoundError: [Errno 2] No such file or directory: '/csqext.cpp'

```

**Comment by AniketKumar2500** [comment]
Actually as we have made csq global so the file processing is a little bit deformed I will fix that again.
