### ISSUE TITLE
CSQ Compiler Does Not Detect Syntax Errors During Compilation 

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq#232]
**Issue Description:**
When testing PR #231, I intentionally introduced a syntax error in the CSQ code by omitting the colon in the if statement. According to the expected behavior, the CSQ compiler should identify such errors during compilation and produce appropriate syntax error messages. However, during the testing process, the CSQ compiler did not raise syntax errors, and the issue was only detected when the resulting C++ code was compiled.

**Csq**
```

if 1<2
 print("HelloWorld")
```

**Error by CPP compiler**
```

hello.cpp: In function ‘int main(int, char**)’:
hello.cpp:6:20: error: expected primary-expression before ‘)’ token
    6 | if(_cond_(i_val(1)<)){
      |                    ^
hello.cpp:7:8: error: could not convert ‘(const char*)("HelloWorld")’ from ‘const char*’ to ‘Cell’
    7 | print(("HelloWorld"));
      |       ~^~~~~~~~~~~~~
      |        |
      |        const char*

```

**Expected Behavior:**
The CSQ compiler should perform thorough syntax checking during compilation of CSQ code and immediately report any errors encountered. This behavior is crucial for identifying and resolving issues early in the development process.

**Current Behavior:**
The CSQ compiler does not raise syntax errors during compilation when they are present in the CSQ code. The errors are only discovered during the subsequent compilation of the generated C++ code.

**Steps to Reproduce:**
1. Write CSQ code with intentional syntax errors (e.g., missing colon in if statement).
2. Attempt to compile the CSQ code using the CSQ compiler.
3. Observe that the CSQ compiler does not produce syntax error messages.
4. Proceed with the compilation of the generated C++ code, which then reveals the syntax errors.

**[NOTE] Before Testing and Merging PR #231 We Should Solve This Issue**

**Comment by WithSJ** [comment]
After retesting PR #233, I identified errors from both the csq compiler and Python3 compiler. 
```
At Line 1
SyntaxError: Missing colon at the end in the used if stmt.
Traceback (most recent call last):
  File "/home/withsj/.local/bin/csq", line 35, in <module>
    compiled_code = Compile(lines)
  File "/home/withsj/.local/bin/Compiler/Parser/parser.py", line 451, in Compile
    while indent_level != scope_stack[-1].indent_level:
IndexError: list index out of range

```
The csq compiler produced a SyntaxError at Line 1, stating a missing colon at the end of the used if statement. Additionally, the Python3 compiler raised an IndexError with the following traceback:

 
Csq Error
`At Line 1`
`SyntaxError: Missing colon at the end in the used if stmt.`


Python3 Error
```
Traceback (most recent call last):
  File "/home/withsj/.local/bin/csq", line 35, in <module>
    compiled_code = Compile(lines)
  File "/home/withsj/.local/bin/Compiler/Parser/parser.py", line 451, in Compile
    while indent_level != scope_stack[-1].indent_level:
IndexError: list index out of range
```

I think to solve this issue Csq compiler should exit() after produce error
